version: '3.1'
services:
  db:
    image: postgres:13
    restart: always
    ports:
      - 5430:5432
    environment:
      - POSTGRES_USER=${POSTGRESQL_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DB=${POSTGRESQL_DATABASE}
    env_file:
      - .env
    volumes:
      - ./.db:/var/lib/postgresql

  boom:
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    ports:
       - 4000:4000

networks:
  default:
    external:
      name: boom_network