* BOOM

BOOM is a simple application to manage your books in a database.

** Development environment

- Install elixir/erlang using `asdf`

Information to install asdf can be found [here](https://github.com/asdf-vm/asdf)

#+BEGIN_SRC bash
asdf plugin-add erlang https://github.com/asdf-vm/asdf-erlang
asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir
#+END_SRC

#+BEGIN_SRC bash
asdf install
#+END_SRC

or install Erlang and Elixir on your machine.

*** Development environment variables

In the [.env](.env) file environments vars needs to be defined for the local environments. Those need to be loaded when working with this project. To do so, one can manually execute:

#+BEGIN_SRC bash
source .env
#+END_SRC

or automate this process using [direnv](https://direnv.net/).

#+BEGIN_SRC bash
* Install direnv using brew
$ brew install direnv

* From the project folder
$ direnv allow
#+END_SRC

Continue with the instructions [here](https://github.com/direnv/direnv*setup)

*** Development environment database

- Install docker&docker-compose

Information to install docker can be found [here](https://docs.docker.com/get-docker/)
Information to install docker-compose can be found [here](https://docs.docker.com/compose/install/)

Set up postgresql database:

#+BEGIN_SRC bash
$ docker network create boom_network
$ docker-compose up
#+END_SRC

** Endpoints :verb:

*** Get a book given ISBN

get http://localhost:4000/api/books/9780123456789
Content-Type: application/json

*** Get all books (limit 50 by default)

get http://localhost:4000/api/books
Content-Type: application/json

*** Get books filtering

get http://localhost:4000/api/books?limit=10&title=Sample Title
Content-Type: application/json

Possible query params: - title - author - publisher - edition

*** Add a new book to the database

post http://localhost:4000/api/books
Content-Type: application/json

  {
      "ISBN": "1234567890",
      "title": "Sample Title",
      "author": "The person who wrote this",
      "publisher": "BOOM books",
      "edition": "1"
  }

** Authors

* **Alfedi** - *initial work* [Alfedi](https://github.com/Alfedi/BOOM)
* **Ironjanowar** - *continued work* [Ironjanowar](https://github.com/Ironjanowar)
* **FORGIS98** - *continued work* [FORGIS98](https://github.com/FORGIS98)
* **kamiyuzu** - *continued work* [kamiyuzu](https://github.com/kamiyuzu)
* **rockneurotiko** - *continued work* [rockneurotiko](https://github.com/rockneurotiko)

*** Very special thanks

To [@samgh96](https://github.com/samgh96) for suggesting such an
incredible name and not letting me keep the awful one.